Http:
# Proxy: socks5://127.0.0.1:39050
Ftx:
  GroupedOrderBook:
    Parquet:
      Enabled: false
      PairFilter: 
        - BTC-PERP
        - ^BTC-MOVE.*
        - ^BTC/USDT?$
        - ETH-PERP
        - ^ETH/USDT?$
        - SOL-PERP
        - ^SOL/USDT?$
    Task:
      Period: 60000
      Enabled: false
      
  RegroupedOrderBook:
    Parquet:
      Enabled: true
      HighCompression: true
    Task:
      Enabled: false
      
  FutureStats:
    Task:
      Enabled: false
      
Bitfinex:
  OrderBook:
    Parquet:
      Enabled: false
    Task:
      Enabled: true
      Period: 60000
      
  OrderBookP0:
    PairFilter:
      - BTC*
      - ETH*
      - XRP*

Trade:
  Collector:
    LockTable: false
    MaxParallelism: 8
  PairFilter:
    - BTC/USD
    - BTC-PERP
    - ETH/USD
    - ETH-PERP
    - XRP/USD
    - XRP-PERP
    - USDT/USD
    - USDT-PERP
    - SOL/USD
    - SOL-PERP
    - BNB/USD
    - BNB-PERP
    - RAY/USD
    - RAY-PERP
    - FTT/USD
    - FTT-PERP
    - SRM/USD
    - SRM-PERP
    #- EOS/USD
    #- EOS-PERP
    - DOGE/USD
    - DOGE-PERP
    - AAVE/USD
    - AAVE-PERP
    - TRX/USD
    - TRX-PERP
    - COMP/USD
    - COMP-PERP
    - FTM/USD
    - FTM-PERP
    - LINK/USD
    - LINK-PERP
    #- CHZ-PERP
    #- CHZ/USD
      
  Aggregate:
    LockTable: false
    MaxParallelism: 4
    ResamplePeriods:
      - 60000
      - 300000
      - 3600000
    ResampleOffsets: 
      - 10000
      - 60000
      - 0
    

Postgres:
  ConnectionString: "Host=127.0.0.1;Username=cryptodduser;Password=cryptouserpass;Database=cryptodd;Port=5432;ConnectionLifetime=600;Keepalive=60;Application Name=cryptodd"
  