Http:
# Proxy: socks5://127.0.0.1:39050
Ftx:
  GroupedOrderBook:
    Parquet:
      Enable: true
      PairFilter: 
        - BTC-PERP
        - BTC-MOVE.*
        - ^BTC/USD*$
        - ETH-PERP
        - ^ETH/USD*$
        - SOL-PERP
        - ^SOL/USD*$
    Task:
      Period: 60000
  RegroupedOrderBook:
    Parquet:
      HighCompression: true
  