Http:
# Proxy: socks5://127.0.0.1:39050
Ftx:
  GroupedOrderBook:
    Parquet:
      Enable: true
      PairFilter: 
        - BTC-PERP
        - ^BTC-MOVE.*
        - ^BTC/USDT?$
        - ETH-PERP
        - ^ETH/USDT?$
        - SOL-PERP
        - ^SOL/USDT?$
    Task:
      Period: 60000
  RegroupedOrderBook:
    Parquet:
      HighCompression: true
  