name: Build and Test project using dotnet

on: [push, pull_request]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Test using Coverlet Code Coverage
        run: |
              dotnet test --configuration Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=json,cobertura,lcov,teamcity,opencover
              cp CryptoDumper.Tests/TestResults/*/coverage.info CryptoDumper.Tests/TestResults/coverage.info
        timeout-minutes: 5
      - name: Upload Code Coverage to Coveralls      
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN }} 
          path-to-lcov: CryptoDumper.Tests/TestResults/coverage.info
      - name: Create artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cryptodumper_${{ matrix.os }}_${{ matrix.dotnet-version }}
          path: CryptoDumper.Console/bin/Release/*
